"""add theme to profiles

Revision ID: 4972b8951563
Revises: 56bca5c9d2a1
Create Date: 2026-08-31 22:19:58.018952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4972b8951563'
down_revision: Union[str, None] = '56bca5c9d2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('theme', sa.String(length=20), nullable=False, server_default='classic')
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
