"""add view_count to profiles and projects

Revision ID: 56bca5c9d2a1
Revises: f8250536f511
Create Date: 2026-08-31 21:49:19.366941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '56bca5c9d2a1'
down_revision: Union[str, None] = 'f8250536f511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('view_count', sa.Integer(), nullable=False, server_default=sa.text("0"))
        )

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('view_count', sa.Integer(), nullable=False, server_default=sa.text("0"))
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('view_count')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('view_count')

    # ### end Alembic commands ###
